apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: jenkins-x-299818/hands-on-continuous-integration-and-delivery-with-jenkins-x-and-kubernetes
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: hands-on-continuous-integration-and-delivery-with-jenkins-x-and-kubernetes
        chartPath: charts/hands-on-continuous-integration-and-delivery-with-jenkins-x-and-kubernetes
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
          image.tag: '{{.DIGEST_HEX}}'
